---
driver:
  name: docker

platforms:
  - name: manage_operator
    image: quay.io/rockylinux/rockylinux:9
    pre_build_image: true

provisioner:
  name: ansible
  config_options:
    defaults:
      roles_path: ../../roles
  inventory:
    hosts:
      all:
        hosts:
          manage_operator:
            ansible_connection: docker
  playbooks:
    converge: converge.yml
    verify: verify.yml

verifier:
  name: ansible
