---
namespace: lit
name: ocp
version: 1.0.0
readme: README.md
description: >
  Opinionated Ansible collection for Red Hat OpenShift Container Platform
  in the ModuLix ecosystem. Provides roles for cluster
  bring-up, day-2 operations and platform services on top of OpenShift.

repository: "https://github.com/lightning-it/ansible-collection-ocp"
authors:
  - "Lightning IT"
license:
  - GPL-2.0-only
tags:
  - ocp
  - openshift
  - kubernetes
  - platform
  - day2
  - automation
  - devops
  - infrastructure

dependencies:
  ansible.posix: "*"
  kubernetes.core: "*"
  community.hashi_vault: "*"
  community.crypto: "*"
  community.vmware: "*"

build_ignore:
  - node_modules
  - vagrant
  - .git
  - .github
  - .gitignore
  - .molecule
  - ansible_collections
  - infra
  - "*.terraform*"
  - "*.tar.gz"
