---
namespace: lit
name: ocp
version: 1.3.15
readme: README.md
description: Opinionated Ansible collection for Red Hat OpenShift Container Platform
  in the ModuLix ecosystem. Provides roles for cluster bring-up, day-2 operations
  and platform services on top of OpenShift.
repository: https://github.com/lightning-it/ansible-collection-ocp
authors:
  - Lightning IT
license:
  - MIT
tags:
  - modulix
  - ocp
  - openshift
  - kubernetes
  - automation
  - devops
  - infrastructure
dependencies:
  ansible.posix: '*'
  ansible.utils: '*'
  community.general: '>=11.4.9,<12.0.0'
  community.docker: '*'
  kubernetes.core: '*'
  community.hashi_vault: '*'
  community.crypto: '*'
  community.vmware: '5.10.0'
build_ignore:
  - node_modules
  - vagrant
  - .git
  - .github
  - .gitignore
  - .molecule
  - ansible_collections
  - infra
  - '*.terraform*'
  - '*.tar.gz'
