---
driver:
  name: docker

platforms:
  - name: ocp_install_upi
    image: quay.io/rockylinux/rockylinux:9
    pre_build_image: true

provisioner:
  name: ansible
  config_options:
    defaults:
      roles_path: ../../roles
  inventory:
    hosts:
      all:
        hosts:
          ocp_install_upi:
            ansible_connection: docker
  playbooks:
    converge: converge.yml
    verify: verify.yml

verifier:
  name: ansible
