---
- name: Test common install agent switches
  ansible.builtin.assert:
    that:
      - install_agent_provider in ['vsphere', 'baremetal', 'external']
      - install_agent_platform in ['vsphere', 'baremetal', 'none']
      - install_agent_run_assets is boolean
      - install_agent_run_wait is boolean
      - install_agent_run_post is boolean
      - install_agent_run_setup_nodes is boolean
      - install_agent_power_on_nodes is boolean
      - install_agent_skip_download is boolean
      - install_agent_write_kube_credentials is boolean
      - install_agent_control_plane_replicas | int >= 1
      - install_agent_compute_replicas | int >= 0
      - install_agent_nodes is sequence
      - install_agent_nodes is not string
      - install_agent_agent_iso_path | length > 0

- name: Test required values for platform vsphere
  ansible.builtin.assert:
    that:
      - install_agent_api_vip | length > 0
      - install_agent_apps_vip | length > 0
      - install_agent_vcenter_hostname | length > 0
      - install_agent_vcenter_password | length > 0
      - install_agent_vcenter_username | length > 0
      - install_agent_vsphere_cluster | length > 0
      - install_agent_vsphere_datacenter | length > 0
      - vmware_vsphere_vmware_iso_datastore | length > 0
      - install_agent_vsphere_network | length > 0
  when: install_agent_platform == 'vsphere'

- name: Test required values for OCP
  ansible.builtin.assert:
    that:
      - install_agent_base_domain | length > 0
      - install_agent_cluster_name | length > 0
      - install_agent_gateway | length > 0
      - install_agent_gateway | length > 0
      - install_agent_dns_servers | length > 0

- name: Test required explicit node values
  ansible.builtin.assert:
    that:
      - install_agent_node.hostname | default('', true) | length > 0
      - >-
        install_agent_node.role | default('', true)
        in ['master', 'worker', 'control', 'control-plane', 'compute', 'infra']
      - install_agent_node.mac | default('', true) | length > 0
    quiet: true
  loop: "{{ install_agent_nodes }}"
  loop_control:
    loop_var: install_agent_node
    label: "{{ install_agent_node.hostname | default('install-agent-node') }}"
