---
- name: Test required values for platform vsphere
  ansible.builtin.assert:
    that:
      - install_agent_api_vip | length > 0
      - install_agent_apps_vip | length > 0
      - install_agent_vcenter_hostname | length > 0
      - install_agent_vcenter_password | length > 0
      - install_agent_vcenter_username | length > 0
      - install_agent_vsphere_cluster | length > 0
      - install_agent_vsphere_datacenter | length > 0
      - vvs_vmware_iso_datastore | length > 0
      - install_agent_vsphere_network | length > 0
  when: install_agent_platform == 'vsphere'

- name: Test required values for OCP
  ansible.builtin.assert:
    that:
      - install_agent_base_domain | length > 0
      - install_agent_cluster_name | length > 0
      - install_agent_gateway | length > 0
      - install_agent_gateway | length > 0
      - install_agent_dns_servers | length > 0
      - install_agent_ca_o | length > 0
