---
- name: Skip operator management (test/stub mode)
  ansible.builtin.meta: end_play
  when: manage_operator_skip | bool

- name: Debug {{ manage_operator_name }}
  ansible.builtin.debug:
    verbosity: 2
    msg: |
      manage_operator_api_version: {{ manage_operator_api_version }}
      manage_operator_approve: {{ manage_operator_approve }}
      manage_operator_channel: {{ manage_operator_channel }}
      manage_operator_create_namespace: {{ manage_operator_create_namespace }}
      manage_operator_deployment_name: {{ manage_operator_deployment_name }}
      manage_operator_name: {{ manage_operator_name }}
      manage_operator_namespace: {{ manage_operator_namespace }}
      manage_operator_group_name: {{ manage_operator_group_name }}
      manage_operator_plan: {{ manage_operator_plan }}
      manage_operator_source: {{ manage_operator_source }}
      manage_operator_source_namespace: {{ manage_operator_source_namespace }}
      manage_operator_starting_csv: {{ manage_operator_starting_csv }}
      manage_operator_state: {{ manage_operator_state }}
      manage_operator_target_namespaces: {{ manage_operator_target_namespaces }}

- name: Create project {{ manage_operator_namespace }}
  kubernetes.core.k8s:
    state: present
    definition: |
      apiVersion: project.openshift.io/v1
      kind: Project
      metadata:
        name: "{{ manage_operator_namespace }}"
      {% if manage_operator_project_metadata_extras | length > 0 %}
        {{ manage_operator_project_metadata_extras | indent(8, false) }}
      {% endif %}
  when:
    - manage_operator_state != 'absent'
    - manage_operator_create_namespace | bool

- name: Check if OperatorGroup exists in {{ manage_operator_namespace }}
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1
    kind: OperatorGroup
    namespace: "{{ manage_operator_namespace }}"
  register: operatorgroup_info
  ignore_errors: true

- name: Set fact if OperatorGroup exists
  ansible.builtin.set_fact:
    operatorgroup_exists: "{{ operatorgroup_info.resources | length > 0 }}"

- name: Create OperatorGroup if it does not exist
  kubernetes.core.k8s:
    state: present
    definition: |
      apiVersion: operators.coreos.com/v1
      kind: OperatorGroup
      metadata:
        name: "{{ manage_operator_group_name }}"
        namespace: "{{ manage_operator_namespace }}"
      {% if manage_operator_target_namespaces | bool %}
      spec:
        targetNamespaces:
          - "{{ manage_operator_namespace }}"
      {% endif  %}
  when:
    - not operatorgroup_exists
    - manage_operator_state != 'absent'

- name: Set operator subscription to state {{ manage_operator_state }}
  kubernetes.core.k8s:
    state: "{{ manage_operator_state }}"
    definition: |
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: "{{ manage_operator_name }}"
        namespace: "{{ manage_operator_namespace }}"
      spec:
        channel: {{ manage_operator_channel }}
        installPlanApproval: "{{ manage_operator_plan }}"
        source: {{ manage_operator_source }}
        sourceNamespace: {{ manage_operator_source_namespace }}
        name: {{ manage_operator_name }}
      {% if manage_operator_starting_csv | length > 0 %}
        startingCSV: {{ manage_operator_starting_csv }}
      {% endif  %}
      {% if manage_operator_subscription_extras | length > 0 %}
        {{ manage_operator_subscription_extras | indent(2, false) }}
      {% endif  %}
  register: subscription_out
  when: manage_operator_state != 'absent'

- name: Wait for subscription
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: "{{ manage_operator_name }}"
    namespace: "{{ manage_operator_namespace }}"
  register: output_info
  until: >-
    output_info.resources
    | json_query(
      '[*].status.conditions[?reason==`AllCatalogSourcesHealthy`][].status'
    )
    | select('match', 'False')
    | list
    | length == 1
  delay: 10
  retries: 60
  when:
    - manage_operator_plan == 'Manual'
    - manage_operator_state != 'absent'
    - subscription_out.changed

- name: Check for pending approval
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: "{{ manage_operator_name }}"
    namespace: "{{ manage_operator_namespace }}"
  register: subscription_info
  until: >
    subscription_info.resources
    | map(attribute='status.installplan.kind')
    | select('defined')
    | list
    | unique == ['InstallPlan']
  delay: 10
  retries: 60
  when:
    - manage_operator_plan == 'Manual'
    - manage_operator_state != 'absent'

- name: Wait for install plan and approve install plan
  vars:
    manage_operator_pending_approval: >-
      {{
        subscription_info.resources
        | selectattr('status.conditions', 'defined')
        | map(attribute='status.conditions')
        | sum(start=[])
        | selectattr('reason', 'equalto', 'RequiresApproval')
        | selectattr('status', 'equalto', 'True')
        | list
        | length > 0
      }}
  when:
    - manage_operator_approve | bool
    - manage_operator_plan == 'Manual'
    - manage_operator_state != 'absent'
  block:

    - name: >-
        Get current operator currentCSV in {{ manage_operator_namespace }}
      kubernetes.core.k8s_info:
        api_version: operators.coreos.com/v1alpha1
        kind: Subscription
        name: "{{ manage_operator_name }}"
        namespace: "{{ manage_operator_namespace }}"
      register: subscription_info
      until: >
        subscription_info.resources[0].status.currentCSV is defined and
        subscription_info.resources[0].status.currentCSV | length > 0
      retries: 15
      delay: 10
      when: manage_operator_starting_csv | length == 0

    - name: Set fact manage_operator_starting_csv_search
      ansible.builtin.set_fact:
        manage_operator_starting_csv_search: >-
          {{ subscription_info.resources[0].status.currentCSV
               if (manage_operator_starting_csv | length == 0)
               else manage_operator_starting_csv }}

    - name: >-
        Wait for install plan with correct CSV in
        {{ manage_operator_namespace }}
      kubernetes.core.k8s_info:
        api_version: operators.coreos.com/v1alpha1
        kind: InstallPlan
        namespace: "{{ manage_operator_namespace }}"
      register: installplans_info
      until: >
        installplans_info.resources
        | selectattr('spec', 'defined')
        | selectattr('spec.clusterServiceVersionNames', 'defined')
        | selectattr(
          'spec.clusterServiceVersionNames',
          'contains',
          manage_operator_starting_csv_search
        )
        | list
        | length > 0
      retries: 10
      delay: 6
      when: manage_operator_pending_approval

    - name: Set matched install plans
      ansible.builtin.set_fact:
        matching_installplans: >-
          {{ installplans_info.resources
             | selectattr('spec', 'defined')
             | selectattr('spec.clusterServiceVersionNames', 'defined')
             | selectattr(
               'spec.clusterServiceVersionNames',
               'contains',
               manage_operator_starting_csv_search
             )
             | list }}
      when: manage_operator_pending_approval

    - name: Approve installation
      kubernetes.core.k8s:
        merge_type: merge
        definition:
          apiVersion: operators.coreos.com/v1alpha1
          kind: InstallPlan
          metadata:
            name: "{{ item.metadata.name }}"
            namespace: "{{ manage_operator_namespace }}"
          spec:
            approved: true
      loop: "{{ matching_installplans }}"
      when: manage_operator_pending_approval
      no_log: true

- name: Wait for operator deployment
  when:
    - "manage_operator_state != 'absent'"
    - "manage_operator_deployment_name | length > 0"
  kubernetes.core.k8s_info:
    api_version: "{{ manage_operator_api_version }}"
    kind: Deployment
    name: "{{ manage_operator_deployment_name }}"
    namespace: "{{ manage_operator_namespace }}"
    wait: true
    wait_timeout: 30
  register: output_info
  until: >
    output_info.resources
    | selectattr('status.conditions', 'defined')
    | map(attribute='status.conditions')
    | sum(start=[])
    | selectattr('reason', 'equalto', 'MinimumReplicasAvailable')
    | selectattr('status', 'equalto', 'True')
    | list
    | length == 1
  delay: 10
  retries: 60

- name: Wait for operator deployment per label
  when:
    - manage_operator_state != 'absent'
    - manage_operator_deployment_name | length == 0
    - manage_operator_deployment_label | length > 0
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    namespace: "{{ manage_operator_namespace }}"
    label_selectors:
      - "{{ manage_operator_deployment_label }}"
  register: deployment_info
  until: >
    deployment_info.resources
    | selectattr('status.conditions', 'defined')
    | selectattr(
      'status.conditions',
      'selectattr',
      'reason',
      'equalto',
      'MinimumReplicasAvailable'
    )
    | map(attribute='status.conditions')
    | map('selectattr', 'reason', 'equalto', 'MinimumReplicasAvailable')
    | map('first')
    | map(attribute='status')
    | list
    | first == 'True'
  retries: 15
  delay: 30

- name: Get current operator installedCSV in {{ manage_operator_namespace }}
  when: manage_operator_state == 'absent'
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: "{{ manage_operator_name }}"
    namespace: "{{ manage_operator_namespace }}"
  register: subscription_info

- name: Set installed CSV fact
  ansible.builtin.set_fact:
    manage_operator_installed_csv: >-
      {{
        subscription_info.resources[0].status.installedCSV
      }}
  when:
    - manage_operator_state == 'absent'
    - subscription_info.resources[0].status.installedCSV is defined

- name: >-
    Delete ClusterServiceVersion
    {{ manage_operator_installed_csv | default('') }}
  when: manage_operator_state == 'absent'
  kubernetes.core.k8s:
    state: absent
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    name: "{{ manage_operator_installed_csv }}"
    namespace: "{{ manage_operator_namespace }}"
  register: csv_uninstall

- name: Delete Subscription {{ manage_operator_name }}
  when: manage_operator_state == 'absent'
  kubernetes.core.k8s:
    state: absent
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: "{{ manage_operator_name }}"
    namespace: "{{ manage_operator_namespace }}"
  register: subscription_uninstall

- name: Set fact to empty
  ansible.builtin.set_fact:
    manage_operator_starting_csv: ''
    manage_operator_starting_csv_search: ''
    manage_operator_subscription_extras: ''
